# Generated by Django 6.0.5 on 2026-05-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_alter_lesson_options"),
        ("users", "0003_payment_is_successful_payment_payment_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="lms.course",
                verbose_name="Оплаченный курс",
            ),
        ),
    ]
